# Generated by Django 5.2.17 on 2026-09-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('primary_language', models.CharField(blank=True, max_length=100)),
                ('language_bytes', models.JSONField(blank=True, default=dict)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='developers.developer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commits', models.PositiveIntegerField(default=0)),
                ('pull_requests', models.PositiveIntegerField(default=0)),
                ('issues', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('exact', 'Exact (from public events)'), ('estimated', 'Estimated (proportional from yearly totals)')], default='estimated', max_length=20)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to='developers.developer')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['developer', 'date'], name='developers__develop_b7f4d3_idx')],
                'unique_together': {('developer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_snapshots', to='developers.developer')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('developer', 'date')},
            },
        ),
    ]
